### ISSUE TITLE
《EFT - 文章创作平台》BUG 汇总

### ISSUE THREAD

**Issue by pingan8787** [pingan8787/Leo-JavaScript#3]
BUG 汇总回复格式如下： 

一、BUG描述：
图标错啦~

二、正常结果：
图标要正常显示

**Comment by webzhouyan** [comment]
1.目录图片下的文字 上和下 位置反了
2.  清理目录插件 引用少些括号
`const {CleanWebpackPlugin} = require('clean-webpack-plugin');`

**Comment by pingan8787** [comment]
> 1.目录图片下的文字上和下位置反了
> 2。清理目录插件引用写些括号
> `const {CleanWebpackPlugin} = require('clean-webpack-plugin');`

**Comment by pingan8787** [comment]
@webzhouyan 
关于文章的错误地方，可以在[《《Cute-JavaScript》系列文章勘误登记》](https://github.com/pingan8787/Leo-JavaScript/issues/1) 提交哈。

这两个地方我已经修改好了，图片可能还会有CDN缓存问题。
